image: python:latest

stages:
  - test


unit-test-job:
  stage: test
  script:
    - TESTS = $(ls tests)
    - if [[ $TESTS ]]; then
        python -m pytest -n=4 -rN --tb=line -v -k tests 
        --reruns 3 --reruns-delay 3

lint-test-job:
  stage: test
  script:
    - echo $(pwd)
    - pip install flake8
    - flake8 --verbose .
