image: docker:latest

stages:
  - build
  - test

build:
  stage: build
  variables:
    http_proxy: <your-proxy>
    https_proxy: <your-proxy>
    no_proxy: <your-no-proxy>
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/env/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"

unit-test-job:
  stage: test
  script:
    - pip install pytest
    - |-
      if [[ $(ls tests) ]]; then
        python -m pytest -rN --tb=line -v -k tests 
        --reruns 3 --reruns-delay 3
      fi

lint-test-job:
  stage: test
  script:
    - echo $(pwd)
    - pip install flake8
    - flake8 --verbose .
