image: python:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - apt-get update
    - apt-get install ca-certificates curl gnupg
    - apt-get update
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - chmod a+r /etc/apt/keyrings/docker.gpg
    - apt-get -y install coreutils
    - apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - docker build -f enc/Dockerfile -t myapp_debug .

unit-test-job:
  stage: test
  script:
    - pip install pytest
    - |-
      if [[ $(ls tests) ]]; then
        python -m pytest -rN --tb=line -v -k tests 
        --reruns 3 --reruns-delay 3
      fi

lint-test-job:
  stage: test
  script:
    - echo $(pwd)
    - pip install flake8
    - flake8 --verbose .
